### ISSUE TITLE
Hi, DaniDiaz.

### ISSUE THREAD

**Issue by samuf92** [DaniDiaz71/AnycubicChironUpgrade#1]
I really interested to get this change on my Chiron too, actually i use Coolio Marlin 2.0 version for Chiron 
https://github.com/coolio986/Marlin_2.0.x_Anycubic_Chiron

Have you found a way tu use the default chiron display with SKR board??

**Comment by DaniDiaz71** [comment]
Hi! I was able to do it and now it's working but unfortunately before upload source code to Github my hard disk died :( So the only thing i have it's the compiled hex file. I can share it but I'm not sure if this will work on any other printer because i have rewired some stuff.
Anyway check Marlin last version because I think some developers include Chiron stock display to Configuration.h. Last version has this line: //#define ANYCUBIC_LCD_CHIRON so I guess there should be stock display support but I didn't try it. Drop me a line if you test it :)
Best regards!
